export const defaultImages = [
  {
    id: "XkB-uA7p9NI",
    slug: "brown-rock-formation-on-brown-field-during-daytime-XkB-uA7p9NI",
    alternative_slugs: {
      en: "brown-rock-formation-on-brown-field-during-daytime-XkB-uA7p9NI",
      es: "formacion-de-rocas-marrones-en-campo-marron-durante-el-dia-XkB-uA7p9NI",
      ja: "日中の褐色地に褐色岩層-XkB-uA7p9NI",
      fr: "formation-rocheuse-brune-sur-un-champ-brun-pendant-la-journee-XkB-uA7p9NI",
      it: "formazione-rocciosa-marrone-su-campo-marrone-durante-il-giorno-XkB-uA7p9NI",
      ko: "낮-동안-갈색-들판에-갈색-암석-형성-XkB-uA7p9NI",
      de: "braune-felsformation-auf-braunem-feld-tagsuber-XkB-uA7p9NI",
      pt: "formacao-rochosa-marrom-no-campo-marrom-durante-o-dia-XkB-uA7p9NI",
    },
    created_at: "2020-05-07T23:32:53Z",
    updated_at: "2024-09-22T00:37:50Z",
    promoted_at: "2020-05-10T13:36:02Z",
    width: 3872,
    height: 2581,
    color: "#a6a6a6",
    blur_hash: "LaC$.dbIWCWC~poff6ay.8s:oLj[",
    description: "the wild west\nig @bybengranados",
    alt_description: "brown rock formation on brown field during daytime",
    breadcrumbs: [
      {
        slug: "images",
        title: "1,000,000+ Free Images",
        index: 0,
        type: "landing_page",
      },
      {
        slug: "nature",
        title: "Nature Images",
        index: 1,
        type: "landing_page",
      },
      {
        slug: "landscape",
        title: "Landscape Images & Pictures",
        index: 2,
        type: "landing_page",
      },
    ],
    urls: {
      raw: "https://images.unsplash.com/photo-1588894051921-5e60abf4eab9?ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1588894051921-5e60abf4eab9?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1588894051921-5e60abf4eab9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1588894051921-5e60abf4eab9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1588894051921-5e60abf4eab9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1588894051921-5e60abf4eab9",
    },
    links: {
      self: "https://api.unsplash.com/photos/brown-rock-formation-on-brown-field-during-daytime-XkB-uA7p9NI",
      html: "https://unsplash.com/photos/brown-rock-formation-on-brown-field-during-daytime-XkB-uA7p9NI",
      download:
        "https://unsplash.com/photos/XkB-uA7p9NI/download?ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8",
      download_location:
        "https://api.unsplash.com/photos/XkB-uA7p9NI/download?ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8",
    },
    likes: 360,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      nature: {
        status: "approved",
        approved_on: "2021-09-06T13:40:54Z",
      },
      wallpapers: {
        status: "approved",
        approved_on: "2020-05-11T09:21:11Z",
      },
    },
    asset_type: "photo",
    user: {
      id: "P3C6kCwalYs",
      updated_at: "2024-06-05T01:36:27Z",
      username: "bybengranados",
      name: "ben granados",
      first_name: "ben",
      last_name: "granados",
      twitter_username: null,
      portfolio_url: null,
      bio: "based in california",
      location: null,
      links: {
        self: "https://api.unsplash.com/users/bybengranados",
        html: "https://unsplash.com/@bybengranados",
        photos: "https://api.unsplash.com/users/bybengranados/photos",
        likes: "https://api.unsplash.com/users/bybengranados/likes",
        portfolio: "https://api.unsplash.com/users/bybengranados/portfolio",
        following: "https://api.unsplash.com/users/bybengranados/following",
        followers: "https://api.unsplash.com/users/bybengranados/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1588895295594-5f898ca78bfbimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1588895295594-5f898ca78bfbimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1588895295594-5f898ca78bfbimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "bybengranados",
      total_collections: 0,
      total_likes: 0,
      total_photos: 6,
      total_promoted_photos: 2,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: "bybengranados",
        portfolio_url: null,
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: "Canon",
      model: "Canon EOS 5D Mark III",
      name: "Canon, EOS 5D Mark III",
      exposure_time: "1/1000",
      aperture: "11",
      focal_length: "50.0",
      iso: 800,
    },
    location: {
      name: "Trona Pinnacles, California, USA",
      city: null,
      country: "United States",
      position: {
        latitude: 35.617736,
        longitude: -117.368109,
      },
    },
    views: 14868647,
    downloads: 23708,
  },
  {
    id: "m7YpOZhtkBg",
    slug: "water-waves-on-the-shore-m7YpOZhtkBg",
    alternative_slugs: {
      en: "water-waves-on-the-shore-m7YpOZhtkBg",
      es: "olas-de-agua-en-la-orilla-m7YpOZhtkBg",
      ja: "海岸に打ち寄せる水の波-m7YpOZhtkBg",
      fr: "vagues-deau-sur-le-rivage-m7YpOZhtkBg",
      it: "onde-dacqua-sulla-riva-m7YpOZhtkBg",
      ko: "해안의-파도-m7YpOZhtkBg",
      de: "wasserwellen-am-ufer-m7YpOZhtkBg",
      pt: "ondas-de-agua-na-costa-m7YpOZhtkBg",
    },
    created_at: "2020-01-23T06:47:14Z",
    updated_at: "2024-10-08T00:45:34Z",
    promoted_at: "2020-01-23T07:54:02Z",
    width: 6000,
    height: 3375,
    color: "#c0d9f3",
    blur_hash: "L=EMwnt8Rij]?wofWAj]-;jsflay",
    description: "cold sharp ice melting above flowing dark water\n",
    alt_description: "water waves on the shore",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1579761925093-e82084392020?ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1579761925093-e82084392020?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1579761925093-e82084392020?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1579761925093-e82084392020?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1579761925093-e82084392020?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1579761925093-e82084392020",
    },
    links: {
      self: "https://api.unsplash.com/photos/water-waves-on-the-shore-m7YpOZhtkBg",
      html: "https://unsplash.com/photos/water-waves-on-the-shore-m7YpOZhtkBg",
      download:
        "https://unsplash.com/photos/m7YpOZhtkBg/download?ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8",
      download_location:
        "https://api.unsplash.com/photos/m7YpOZhtkBg/download?ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8",
    },
    likes: 89,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      spring: {
        status: "rejected",
      },
      experimental: {
        status: "rejected",
      },
      nature: {
        status: "rejected",
      },
    },
    asset_type: "photo",
    user: {
      id: "XmdtfsR1nAM",
      updated_at: "2024-10-08T14:23:04Z",
      username: "greg_rosenke",
      name: "Greg Rosenke",
      first_name: "Greg",
      last_name: "Rosenke",
      twitter_username: null,
      portfolio_url:
        "https://www.paypal.com/donate?hosted_button_id=QL8N2EPVU8R8W",
      bio: "this is what I saw",
      location: "Comox, British Columbia",
      links: {
        self: "https://api.unsplash.com/users/greg_rosenke",
        html: "https://unsplash.com/@greg_rosenke",
        photos: "https://api.unsplash.com/users/greg_rosenke/photos",
        likes: "https://api.unsplash.com/users/greg_rosenke/likes",
        portfolio: "https://api.unsplash.com/users/greg_rosenke/portfolio",
        following: "https://api.unsplash.com/users/greg_rosenke/following",
        followers: "https://api.unsplash.com/users/greg_rosenke/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1692331056699-a4d6d8ad1e28image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1692331056699-a4d6d8ad1e28image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1692331056699-a4d6d8ad1e28image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "greg.rosenke",
      total_collections: 0,
      total_likes: 1461,
      total_photos: 861,
      total_promoted_photos: 128,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: "greg.rosenke",
        portfolio_url:
          "https://www.paypal.com/donate?hosted_button_id=QL8N2EPVU8R8W",
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: "Canon",
      model: "EOS 80D",
      name: "Canon, EOS 80D",
      exposure_time: "1/250",
      aperture: "5.6",
      focal_length: "64.0",
      iso: 400,
    },
    location: {
      name: null,
      city: null,
      country: null,
      position: {
        latitude: null,
        longitude: null,
      },
    },
    views: 16848086,
    downloads: 6643,
  },
  {
    id: "KTIVMMOXNu8",
    slug: "silhouette-of-person-standing-along-bare-tree-during-nighttime-KTIVMMOXNu8",
    alternative_slugs: {
      en: "silhouette-of-person-standing-along-bare-tree-during-nighttime-KTIVMMOXNu8",
      es: "silueta-de-la-persona-de-pie-a-lo-largo-del-arbol-desnudo-durante-la-noche-KTIVMMOXNu8",
      ja: "夜間に裸の木に沿って立っている人のシルエット-KTIVMMOXNu8",
      fr: "silhouette-dune-personne-debout-le-long-dun-arbre-nu-pendant-la-nuit-KTIVMMOXNu8",
      it: "silhouette-di-persona-in-piedi-lungo-lalbero-nudo-durante-la-notte-KTIVMMOXNu8",
      ko: "야간에-벌거벗은-나무를-따라-서-있는-사람의-실루엣-KTIVMMOXNu8",
      de: "silhouette-einer-person-die-nachts-an-einem-kahlen-baum-steht-KTIVMMOXNu8",
      pt: "silhueta-da-pessoa-em-pe-ao-longo-da-arvore-nua-durante-a-noite-KTIVMMOXNu8",
    },
    created_at: "2015-12-20T17:39:41Z",
    updated_at: "2024-10-08T09:01:07Z",
    promoted_at: "2015-12-20T17:39:41Z",
    width: 6000,
    height: 4000,
    color: "#262626",
    blur_hash: "LKAJ[??bt6M{0LD%Rjt6%2%LofWV",
    description: "Man Tree Stars Cromarty",
    alt_description:
      "silhouette of person standing along bare tree during nighttime",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1450631835004-9b95ff5cd66f?ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1450631835004-9b95ff5cd66f?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1450631835004-9b95ff5cd66f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1450631835004-9b95ff5cd66f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1450631835004-9b95ff5cd66f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1450631835004-9b95ff5cd66f",
    },
    links: {
      self: "https://api.unsplash.com/photos/silhouette-of-person-standing-along-bare-tree-during-nighttime-KTIVMMOXNu8",
      html: "https://unsplash.com/photos/silhouette-of-person-standing-along-bare-tree-during-nighttime-KTIVMMOXNu8",
      download:
        "https://unsplash.com/photos/KTIVMMOXNu8/download?ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8",
      download_location:
        "https://api.unsplash.com/photos/KTIVMMOXNu8/download?ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8",
    },
    likes: 627,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      spirituality: {
        status: "approved",
        approved_on: "2021-02-19T12:43:15Z",
      },
      nature: {
        status: "approved",
        approved_on: "2020-11-19T12:28:04Z",
      },
      wallpapers: {
        status: "approved",
        approved_on: "2020-11-19T12:28:02Z",
      },
    },
    asset_type: "photo",
    user: {
      id: "7BmDZzAnPyA",
      updated_at: "2023-09-13T04:42:39Z",
      username: "jmacpherson",
      name: "Jamie MacPherson",
      first_name: "Jamie",
      last_name: "MacPherson",
      twitter_username: null,
      portfolio_url: null,
      bio: "I am an aerial and astrophotographer from the Highlands of Scotland. I love nothing more than losing myself in wild places. \r\nhttps://www.instagram.com/jamie__macpherson",
      location: "Scottish Highlands",
      links: {
        self: "https://api.unsplash.com/users/jmacpherson",
        html: "https://unsplash.com/@jmacpherson",
        photos: "https://api.unsplash.com/users/jmacpherson/photos",
        likes: "https://api.unsplash.com/users/jmacpherson/likes",
        portfolio: "https://api.unsplash.com/users/jmacpherson/portfolio",
        following: "https://api.unsplash.com/users/jmacpherson/following",
        followers: "https://api.unsplash.com/users/jmacpherson/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1450295627778-f0e7b988536a?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1450295627778-f0e7b988536a?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1450295627778-f0e7b988536a?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "jamie__macpherson",
      total_collections: 0,
      total_likes: 11,
      total_photos: 23,
      total_promoted_photos: 7,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: false,
      for_hire: false,
      social: {
        instagram_username: "jamie__macpherson",
        portfolio_url: null,
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: null,
      model: null,
      name: null,
      exposure_time: null,
      aperture: null,
      focal_length: null,
      iso: null,
    },
    location: {
      name: "Cromarty, United Kingdom",
      city: "Cromarty",
      country: "United Kingdom",
      position: {
        latitude: 57.680609,
        longitude: -4.03467799999999,
      },
    },
    views: 9678983,
    downloads: 43200,
  },
  {
    id: "v3d5uBB26yA",
    slug: "reflections-on-trees-on-lake-v3d5uBB26yA",
    alternative_slugs: {
      en: "reflections-on-trees-on-lake-v3d5uBB26yA",
      es: "reflejos-en-los-arboles-en-el-lago-v3d5uBB26yA",
      ja: "湖に浮かぶ木々の反射-v3d5uBB26yA",
      fr: "reflexions-sur-les-arbres-sur-le-lac-v3d5uBB26yA",
      it: "riflessioni-sugli-alberi-sul-lago-v3d5uBB26yA",
      ko: "호수의-나무에-대한-반사-v3d5uBB26yA",
      de: "reflexionen-uber-baume-auf-dem-see-v3d5uBB26yA",
      pt: "reflexoes-sobre-arvores-no-lago-v3d5uBB26yA",
    },
    created_at: "2019-10-20T07:28:59Z",
    updated_at: "2024-09-07T23:54:08Z",
    promoted_at: "2019-10-21T08:10:05Z",
    width: 5472,
    height: 3078,
    color: "#262626",
    blur_hash: "LkD]}3ayRPofxuofWBfP~qWBWBs:",
    description: "Reflections",
    alt_description: "reflections on trees on lake",
    breadcrumbs: [
      {
        slug: "images",
        title: "1,000,000+ Free Images",
        index: 0,
        type: "landing_page",
      },
      {
        slug: "apps",
        title: "Apps Images & Photos",
        index: 1,
        type: "landing_page",
      },
      {
        slug: "facebook",
        title: "Facebook Photos & Images",
        index: 2,
        type: "landing_page",
      },
    ],
    urls: {
      raw: "https://images.unsplash.com/photo-1571556506946-72f9214736a6?ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1571556506946-72f9214736a6?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1571556506946-72f9214736a6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1571556506946-72f9214736a6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1571556506946-72f9214736a6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1571556506946-72f9214736a6",
    },
    links: {
      self: "https://api.unsplash.com/photos/reflections-on-trees-on-lake-v3d5uBB26yA",
      html: "https://unsplash.com/photos/reflections-on-trees-on-lake-v3d5uBB26yA",
      download:
        "https://unsplash.com/photos/v3d5uBB26yA/download?ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8",
      download_location:
        "https://api.unsplash.com/photos/v3d5uBB26yA/download?ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8",
    },
    likes: 609,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      wallpapers: {
        status: "approved",
        approved_on: "2020-04-06T14:20:10Z",
      },
    },
    asset_type: "photo",
    user: {
      id: "Oo2Slcdyg6A",
      updated_at: "2024-05-18T19:46:56Z",
      username: "mozzillo_cristiano",
      name: "Cristiano Mozzillo",
      first_name: "Cristiano",
      last_name: "Mozzillo",
      twitter_username: null,
      portfolio_url: "https://500px.com/cristianomozzillo",
      bio: null,
      location: "Pisa",
      links: {
        self: "https://api.unsplash.com/users/mozzillo_cristiano",
        html: "https://unsplash.com/@mozzillo_cristiano",
        photos: "https://api.unsplash.com/users/mozzillo_cristiano/photos",
        likes: "https://api.unsplash.com/users/mozzillo_cristiano/likes",
        portfolio:
          "https://api.unsplash.com/users/mozzillo_cristiano/portfolio",
        following:
          "https://api.unsplash.com/users/mozzillo_cristiano/following",
        followers:
          "https://api.unsplash.com/users/mozzillo_cristiano/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1571555533604-2e105410643fimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1571555533604-2e105410643fimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1571555533604-2e105410643fimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "mozzillo_cristiano",
      total_collections: 0,
      total_likes: 9,
      total_photos: 11,
      total_promoted_photos: 1,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: "mozzillo_cristiano",
        portfolio_url: "https://500px.com/cristianomozzillo",
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: "Canon",
      model: "Canon EOS 6D",
      name: "Canon, EOS 6D",
      exposure_time: "1/160",
      aperture: "5.0",
      focal_length: "28.0",
      iso: 100,
    },
    location: {
      name: null,
      city: null,
      country: null,
      position: {
        latitude: null,
        longitude: null,
      },
    },
    views: 22471419,
    downloads: 45381,
  },
  {
    id: "Dw6tBa20afk",
    slug: "aerial-view-of-green-trees-Dw6tBa20afk",
    alternative_slugs: {
      en: "aerial-view-of-green-trees-Dw6tBa20afk",
      es: "vista-aerea-de-arboles-verdes-Dw6tBa20afk",
      ja: "緑の木々の空中写真-Dw6tBa20afk",
      fr: "vue-aerienne-darbres-verts-Dw6tBa20afk",
      it: "veduta-aerea-di-alberi-verdi-Dw6tBa20afk",
      ko: "푸른-나무의-조감도-Dw6tBa20afk",
      de: "luftaufnahme-von-grunen-baumen-Dw6tBa20afk",
      pt: "vista-aerea-de-arvores-verdes-Dw6tBa20afk",
    },
    created_at: "2018-10-21T18:06:05Z",
    updated_at: "2024-08-26T20:13:13Z",
    promoted_at: "2018-10-22T14:30:18Z",
    width: 4000,
    height: 2666,
    color: "#262640",
    blur_hash: "L24e{GtR8xaxx]ozV@V@IAoMxtfk",
    description: "Nature pure",
    alt_description: "aerial view of green trees",
    breadcrumbs: [
      {
        slug: "images",
        title: "1,000,000+ Free Images",
        index: 0,
        type: "landing_page",
      },
      {
        slug: "feelings",
        title: "Feelings Images",
        index: 1,
        type: "landing_page",
      },
      {
        slug: "cool",
        title: "Cool Images & Photos",
        index: 2,
        type: "landing_page",
      },
    ],
    urls: {
      raw: "https://images.unsplash.com/photo-1540144965158-050c0b7769ed?ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1540144965158-050c0b7769ed?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1540144965158-050c0b7769ed?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1540144965158-050c0b7769ed?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1540144965158-050c0b7769ed?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1540144965158-050c0b7769ed",
    },
    links: {
      self: "https://api.unsplash.com/photos/aerial-view-of-green-trees-Dw6tBa20afk",
      html: "https://unsplash.com/photos/aerial-view-of-green-trees-Dw6tBa20afk",
      download:
        "https://unsplash.com/photos/Dw6tBa20afk/download?ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8",
      download_location:
        "https://api.unsplash.com/photos/Dw6tBa20afk/download?ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8",
    },
    likes: 325,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      nature: {
        status: "approved",
        approved_on: "2020-04-06T14:20:12Z",
      },
      wallpapers: {
        status: "approved",
        approved_on: "2020-04-06T14:20:09Z",
      },
    },
    asset_type: "photo",
    user: {
      id: "FEZJF3G26PU",
      updated_at: "2024-07-18T14:49:07Z",
      username: "bruno_kelzer",
      name: "Bruno Kelzer",
      first_name: "Bruno",
      last_name: "Kelzer",
      twitter_username: null,
      portfolio_url: "http://kelzer.de",
      bio: "Home at Karlsruhe (Germany) \r\nUse Sony a7, a7II , a7III and A7IV | SEL90M28G | SEL50F18 | SEL70200G | SEL28F20 | Samyang AF 14MM F2.8 | DJI Mavic Pro",
      location: "Karlsruhe (Germany)",
      links: {
        self: "https://api.unsplash.com/users/bruno_kelzer",
        html: "https://unsplash.com/@bruno_kelzer",
        photos: "https://api.unsplash.com/users/bruno_kelzer/photos",
        likes: "https://api.unsplash.com/users/bruno_kelzer/likes",
        portfolio: "https://api.unsplash.com/users/bruno_kelzer/portfolio",
        following: "https://api.unsplash.com/users/bruno_kelzer/following",
        followers: "https://api.unsplash.com/users/bruno_kelzer/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1662714781152-a880bff877bdimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1662714781152-a880bff877bdimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1662714781152-a880bff877bdimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "this_is_Bruno",
      total_collections: 0,
      total_likes: 172,
      total_photos: 173,
      total_promoted_photos: 33,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: "this_is_Bruno",
        portfolio_url: "http://kelzer.de",
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: "SONY",
      model: "ILCE-7M2",
      name: "SONY, ILCE-7M2",
      exposure_time: "1/800",
      aperture: "2.8",
      focal_length: "14.0",
      iso: 500,
    },
    location: {
      name: "Bad Wildbad, Germany",
      city: "Bad Wildbad",
      country: "Germany",
      position: {
        latitude: 48.751608,
        longitude: 8.54927309999994,
      },
    },
    views: 20304951,
    downloads: 85026,
  },
  {
    id: "TVJPqoSc3bI",
    slug: "green-palm-tree-under-blue-sky-during-daytime-TVJPqoSc3bI",
    alternative_slugs: {
      en: "green-palm-tree-under-blue-sky-during-daytime-TVJPqoSc3bI",
      es: "palmera-verde-bajo-el-cielo-azul-durante-el-dia-TVJPqoSc3bI",
      ja: "昼間の青空に映える緑のヤシの木-TVJPqoSc3bI",
      fr: "palmier-vert-sous-le-ciel-bleu-pendant-la-journee-TVJPqoSc3bI",
      it: "palma-verde-sotto-il-cielo-blu-durante-il-giorno-TVJPqoSc3bI",
      ko: "낮-동안-푸른-하늘-아래-녹색-야자수-TVJPqoSc3bI",
      de: "grune-palme-unter-blauem-himmel-tagsuber-TVJPqoSc3bI",
      pt: "palmeira-verde-sob-o-ceu-azul-durante-o-dia-TVJPqoSc3bI",
    },
    created_at: "2020-02-13T15:21:41Z",
    updated_at: "2024-08-26T20:29:41Z",
    promoted_at: "2020-02-13T15:45:52Z",
    width: 5218,
    height: 7823,
    color: "#40738c",
    blur_hash: "LEA2DRRkF#t78^aewHWCkskCt2f5",
    description: "not cali",
    alt_description: "green palm tree under blue sky during daytime",
    breadcrumbs: [
      {
        slug: "images",
        title: "1,000,000+ Free Images",
        index: 0,
        type: "landing_page",
      },
      {
        slug: "feelings",
        title: "Feelings Images",
        index: 1,
        type: "landing_page",
      },
      {
        slug: "cool",
        title: "Cool Images & Photos",
        index: 2,
        type: "landing_page",
      },
    ],
    urls: {
      raw: "https://images.unsplash.com/photo-1581607267223-75e269eab7ff?ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1581607267223-75e269eab7ff?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1581607267223-75e269eab7ff?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1581607267223-75e269eab7ff?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1581607267223-75e269eab7ff?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1581607267223-75e269eab7ff",
    },
    links: {
      self: "https://api.unsplash.com/photos/green-palm-tree-under-blue-sky-during-daytime-TVJPqoSc3bI",
      html: "https://unsplash.com/photos/green-palm-tree-under-blue-sky-during-daytime-TVJPqoSc3bI",
      download:
        "https://unsplash.com/photos/TVJPqoSc3bI/download?ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8",
      download_location:
        "https://api.unsplash.com/photos/TVJPqoSc3bI/download?ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8",
    },
    likes: 176,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "Vjk_LTngRdc",
      updated_at: "2024-09-10T18:18:15Z",
      username: "matthewlejune",
      name: "Matthew LeJune",
      first_name: "Matthew",
      last_name: "LeJune",
      twitter_username: "MatthewLeJune",
      portfolio_url: "https://matthewlejune.darkroom.tech/",
      bio: "burners.",
      location: "Brooklyn, New York",
      links: {
        self: "https://api.unsplash.com/users/matthewlejune",
        html: "https://unsplash.com/@matthewlejune",
        photos: "https://api.unsplash.com/users/matthewlejune/photos",
        likes: "https://api.unsplash.com/users/matthewlejune/likes",
        portfolio: "https://api.unsplash.com/users/matthewlejune/portfolio",
        following: "https://api.unsplash.com/users/matthewlejune/following",
        followers: "https://api.unsplash.com/users/matthewlejune/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1647744460829-f2bb2e1be625?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1647744460829-f2bb2e1be625?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1647744460829-f2bb2e1be625?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "matthewlejune",
      total_collections: 7,
      total_likes: 7,
      total_photos: 501,
      total_promoted_photos: 68,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: "matthewlejune",
        portfolio_url: "https://matthewlejune.darkroom.tech/",
        twitter_username: "MatthewLeJune",
        paypal_email: null,
      },
    },
    exif: {
      make: "SONY",
      model: "ILCE-7RM3",
      name: "SONY, ILCE-7RM3",
      exposure_time: "1/1250",
      aperture: "6.3",
      focal_length: "45.0",
      iso: 320,
    },
    location: {
      name: "Arizona, USA",
      city: null,
      country: "United States",
      position: {
        latitude: 34.0489281,
        longitude: -111.0937311,
      },
    },
    views: 9367294,
    downloads: 12070,
  },
  {
    id: "oGIr8Fkg3LU",
    slug: "white-and-blue-boat-on-body-of-water-near-rocky-mountain-during-daytime-oGIr8Fkg3LU",
    alternative_slugs: {
      en: "white-and-blue-boat-on-body-of-water-near-rocky-mountain-during-daytime-oGIr8Fkg3LU",
      es: "barco-blanco-y-azul-en-el-cuerpo-de-agua-cerca-de-las-montanas-rocosas-durante-el-dia-oGIr8Fkg3LU",
      ja: "昼間ロッキーマウンテン近くの水域に浮かぶ白と青のボート-oGIr8Fkg3LU",
      fr: "bateau-blanc-et-bleu-sur-le-plan-deau-pres-de-rocky-mountain-pendant-la-journee-oGIr8Fkg3LU",
      it: "barca-bianca-e-blu-sullo-specchio-dacqua-vicino-alla-montagna-rocciosa-durante-il-giorno-oGIr8Fkg3LU",
      ko: "낮-동안-로키-산-근처의-수역에-흰색과-파란색-보트-oGIr8Fkg3LU",
      de: "weisses-und-blaues-boot-tagsuber-auf-einem-gewasser-in-der-nahe-von-rocky-mountain-oGIr8Fkg3LU",
      pt: "barco-branco-e-azul-no-corpo-de-agua-perto-da-montanha-rochosa-durante-o-dia-oGIr8Fkg3LU",
    },
    created_at: "2021-04-25T17:22:59Z",
    updated_at: "2024-10-08T08:15:20Z",
    promoted_at: "2021-04-26T11:33:02Z",
    width: 4000,
    height: 6000,
    color: "#262626",
    blur_hash: "LkEf4-tSt7of~Wo#ofjs-;W=R*ae",
    description: "Vajolet Towers, Dolomites, Italy.",
    alt_description:
      "white and blue boat on body of water near rocky mountain during daytime",
    breadcrumbs: [
      {
        slug: "images",
        title: "1,000,000+ Free Images",
        index: 0,
        type: "landing_page",
      },
      {
        slug: "feelings",
        title: "Feelings Images",
        index: 1,
        type: "landing_page",
      },
      {
        slug: "cool",
        title: "Cool Images & Photos",
        index: 2,
        type: "landing_page",
      },
    ],
    urls: {
      raw: "https://images.unsplash.com/photo-1619371208402-615001f13a45?ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1619371208402-615001f13a45?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1619371208402-615001f13a45?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1619371208402-615001f13a45?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1619371208402-615001f13a45?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1619371208402-615001f13a45",
    },
    links: {
      self: "https://api.unsplash.com/photos/white-and-blue-boat-on-body-of-water-near-rocky-mountain-during-daytime-oGIr8Fkg3LU",
      html: "https://unsplash.com/photos/white-and-blue-boat-on-body-of-water-near-rocky-mountain-during-daytime-oGIr8Fkg3LU",
      download:
        "https://unsplash.com/photos/oGIr8Fkg3LU/download?ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8",
      download_location:
        "https://api.unsplash.com/photos/oGIr8Fkg3LU/download?ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8",
    },
    likes: 649,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      travel: {
        status: "approved",
        approved_on: "2021-07-05T11:01:08Z",
      },
      nature: {
        status: "approved",
        approved_on: "2021-06-30T13:43:16Z",
      },
      wallpapers: {
        status: "approved",
        approved_on: "2021-04-26T12:15:10Z",
      },
    },
    asset_type: "photo",
    user: {
      id: "hFVwZ1l4fHc",
      updated_at: "2024-06-19T01:22:13Z",
      username: "rluijtenant",
      name: "Ruud Luijten",
      first_name: "Ruud",
      last_name: "Luijten",
      twitter_username: "rluijtenant",
      portfolio_url: "http://rluijten.photography",
      bio: "Ruud Luijten is a Belgian-born, self-taught photographer with a passion for the outdoors and the wilderness.",
      location: "Antwerp, Belgium",
      links: {
        self: "https://api.unsplash.com/users/rluijtenant",
        html: "https://unsplash.com/@rluijtenant",
        photos: "https://api.unsplash.com/users/rluijtenant/photos",
        likes: "https://api.unsplash.com/users/rluijtenant/likes",
        portfolio: "https://api.unsplash.com/users/rluijtenant/portfolio",
        following: "https://api.unsplash.com/users/rluijtenant/following",
        followers: "https://api.unsplash.com/users/rluijtenant/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1551771170215-596523649af3?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1551771170215-596523649af3?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1551771170215-596523649af3?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "rluijtenant",
      total_collections: 0,
      total_likes: 0,
      total_photos: 23,
      total_promoted_photos: 11,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: "rluijtenant",
        portfolio_url: "http://rluijten.photography",
        twitter_username: "rluijtenant",
        paypal_email: null,
      },
    },
    exif: {
      make: "NIKON CORPORATION",
      model: "NIKON D7100",
      name: "NIKON CORPORATION, NIKON D7100",
      exposure_time: "1/60",
      aperture: "9",
      focal_length: "36.0",
      iso: 400,
    },
    location: {
      name: "Dolomites, Italy",
      city: null,
      country: null,
      position: {
        latitude: 46.47,
        longitude: 11.621111,
      },
    },
    views: 24834180,
    downloads: 30453,
  },
  {
    id: "bL94YlcB5FI",
    slug: "a-lighthouse-on-a-hill-overlooking-the-ocean-bL94YlcB5FI",
    alternative_slugs: {
      en: "a-lighthouse-on-a-hill-overlooking-the-ocean-bL94YlcB5FI",
      es: "un-faro-en-una-colina-con-vistas-al-oceano-bL94YlcB5FI",
      ja: "海を見下ろす丘の上の灯台-bL94YlcB5FI",
      fr: "un-phare-sur-une-colline-surplombant-locean-bL94YlcB5FI",
      it: "un-faro-su-una-collina-che-domina-loceano-bL94YlcB5FI",
      ko: "바다가-내려다-보이는-언덕-위의-등대-bL94YlcB5FI",
      de: "ein-leuchtturm-auf-einem-hugel-mit-blick-auf-den-ozean-bL94YlcB5FI",
      pt: "um-farol-em-uma-colina-com-vista-para-o-oceano-bL94YlcB5FI",
    },
    created_at: "2023-02-06T08:14:03Z",
    updated_at: "2024-09-05T05:28:26Z",
    promoted_at: "2023-02-06T12:40:01Z",
    width: 4873,
    height: 3249,
    color: "#a6a6a6",
    blur_hash: "LbEVpZt8bHa#?wR+s.j[%2adoeWV",
    description: null,
    alt_description: "a lighthouse on a hill overlooking the ocean",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1675671233507-c8b670d27525?ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1675671233507-c8b670d27525?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1675671233507-c8b670d27525?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1675671233507-c8b670d27525?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1675671233507-c8b670d27525?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1675671233507-c8b670d27525",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-lighthouse-on-a-hill-overlooking-the-ocean-bL94YlcB5FI",
      html: "https://unsplash.com/photos/a-lighthouse-on-a-hill-overlooking-the-ocean-bL94YlcB5FI",
      download:
        "https://unsplash.com/photos/bL94YlcB5FI/download?ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8",
      download_location:
        "https://api.unsplash.com/photos/bL94YlcB5FI/download?ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8",
    },
    likes: 95,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      ugc: {
        status: "approved",
        approved_on: "2024-05-07T08:34:34Z",
      },
      "cozy-moments": {
        status: "rejected",
      },
      "architecture-interior": {
        status: "rejected",
      },
      nature: {
        status: "rejected",
      },
      travel: {
        status: "approved",
        approved_on: "2023-02-15T09:06:17Z",
      },
      wallpapers: {
        status: "approved",
        approved_on: "2023-02-15T08:02:44Z",
      },
      spirituality: {
        status: "approved",
        approved_on: "2023-02-06T18:11:02Z",
      },
    },
    asset_type: "photo",
    user: {
      id: "wmLTsdfFWEU",
      updated_at: "2024-10-08T15:00:55Z",
      username: "nikita_pishchugin",
      name: "Nikita Pishchugin",
      first_name: "Nikita",
      last_name: "Pishchugin",
      twitter_username: null,
      portfolio_url: "https://nikitapishchugin.myportfolio.com",
      bio: "Showing the beauty of the world from architecture to people 🌍",
      location: "Berlin",
      links: {
        self: "https://api.unsplash.com/users/nikita_pishchugin",
        html: "https://unsplash.com/@nikita_pishchugin",
        photos: "https://api.unsplash.com/users/nikita_pishchugin/photos",
        likes: "https://api.unsplash.com/users/nikita_pishchugin/likes",
        portfolio: "https://api.unsplash.com/users/nikita_pishchugin/portfolio",
        following: "https://api.unsplash.com/users/nikita_pishchugin/following",
        followers: "https://api.unsplash.com/users/nikita_pishchugin/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1712439622629-9945649b74e5image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1712439622629-9945649b74e5image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1712439622629-9945649b74e5image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "nikita_pishchugin",
      total_collections: 14,
      total_likes: 772,
      total_photos: 162,
      total_promoted_photos: 40,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: "nikita_pishchugin",
        portfolio_url: "https://nikitapishchugin.myportfolio.com",
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: "Canon",
      model: " EOS 6D Mark II",
      name: "Canon, EOS 6D Mark II",
      exposure_time: "1/200",
      aperture: "9",
      focal_length: "55.0",
      iso: 100,
    },
    location: {
      name: "Ukraine, Crimea",
      city: "Ukrainka",
      country: null,
      position: {
        latitude: 44.886227,
        longitude: 34.139957,
      },
    },
    views: 5279412,
    downloads: 37105,
  },
  {
    id: "QYRL3N0bSX8",
    slug: "a-white-vase-sitting-on-top-of-a-wooden-table-QYRL3N0bSX8",
    alternative_slugs: {
      en: "a-white-vase-sitting-on-top-of-a-wooden-table-QYRL3N0bSX8",
      es: "un-jarron-blanco-sentado-encima-de-una-mesa-de-madera-QYRL3N0bSX8",
      ja: "木製のテーブルの上に座っている白い花瓶-QYRL3N0bSX8",
      fr: "un-vase-blanc-pose-sur-une-table-en-bois-QYRL3N0bSX8",
      it: "un-vaso-bianco-seduto-sopra-un-tavolo-di-legno-QYRL3N0bSX8",
      ko: "나무-테이블-위에-앉아-있는-하얀-꽃병-QYRL3N0bSX8",
      de: "eine-weisse-vase-auf-einem-holztisch-QYRL3N0bSX8",
      pt: "um-vaso-branco-sentado-em-cima-de-uma-mesa-de-madeira-QYRL3N0bSX8",
    },
    created_at: "2022-02-05T13:40:19Z",
    updated_at: "2024-10-08T00:35:59Z",
    promoted_at: "2022-02-05T20:08:01Z",
    width: 8736,
    height: 11648,
    color: "#262626",
    blur_hash: "LJD]MA$%D*IV0Kt8RkWBE2IU%2%2",
    description: "The table setup at the wonderful Moargut in Grossarl.",
    alt_description: "a white vase sitting on top of a wooden table",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1644068339224-e9663375ba44?ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1644068339224-e9663375ba44?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1644068339224-e9663375ba44?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1644068339224-e9663375ba44?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1644068339224-e9663375ba44?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1644068339224-e9663375ba44",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-white-vase-sitting-on-top-of-a-wooden-table-QYRL3N0bSX8",
      html: "https://unsplash.com/photos/a-white-vase-sitting-on-top-of-a-wooden-table-QYRL3N0bSX8",
      download:
        "https://unsplash.com/photos/QYRL3N0bSX8/download?ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8",
      download_location:
        "https://api.unsplash.com/photos/QYRL3N0bSX8/download?ixid=M3w2NjI1MDN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjg0MDQzMjN8",
    },
    likes: 239,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "S3n31jr56o8",
      updated_at: "2024-10-08T02:39:22Z",
      username: "patresinger",
      name: "Patrick Langwallner",
      first_name: "Patrick",
      last_name: "Langwallner",
      twitter_username: "patresinger",
      portfolio_url: "http://www.patrese.at",
      bio: "I am a lifestyle and wedding photographer from Salzburg / Austria. Say hallo on Instagram @patrese",
      location: "Salzburg / Austria",
      links: {
        self: "https://api.unsplash.com/users/patresinger",
        html: "https://unsplash.com/@patresinger",
        photos: "https://api.unsplash.com/users/patresinger/photos",
        likes: "https://api.unsplash.com/users/patresinger/likes",
        portfolio: "https://api.unsplash.com/users/patresinger/portfolio",
        following: "https://api.unsplash.com/users/patresinger/following",
        followers: "https://api.unsplash.com/users/patresinger/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1560256656985-c0a8e0d586a9?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1560256656985-c0a8e0d586a9?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1560256656985-c0a8e0d586a9?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "patrese",
      total_collections: 1,
      total_likes: 34,
      total_photos: 550,
      total_promoted_photos: 185,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: "patrese",
        portfolio_url: "http://www.patrese.at",
        twitter_username: "patresinger",
        paypal_email: null,
      },
    },
    exif: {
      make: "FUJIFILM",
      model: "GFX100S",
      name: "FUJIFILM, GFX100S",
      exposure_time: "1/125",
      aperture: "2.8",
      focal_length: "63.0",
      iso: 50,
    },
    location: {
      name: null,
      city: null,
      country: null,
      position: {
        latitude: null,
        longitude: null,
      },
    },
    views: 4156013,
    downloads: 28674,
  },
];
